-- Tables
CREATE TABLE IF NOT EXISTS Users (
    CNIC INT PRIMARY KEY ,
    Email VARCHAR(40)NOT NULL UNIQUE,
    UserPassword  VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    Province VARCHAR(20) NOT NULL,
    District VARCHAR(20) NOT NULL,
    City VARCHAR(20) NOT NULL,
    Address VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   
);

CREATE TABLE IF NOT EXISTS Unit(
    UnitID INT PRIMARY KEY ,
    BuildingNumber VARCHAR(20) NOT NULL,
    FloorNumber INT NOT NULL,
    OccupiedBy INT,
    UnitProject INT NOT NULL,
    Status ENUM('Vacant', 'Rented', 'Owner_Stay', 'Manager_Assigned', 'Staff_Assigned') NOT NULL
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (OccupiedBy) REFERENCES Users(CNIC) ON DELETE SET NULL ON UPDATE CASCADE
    FOREIGN KEY (UnitProject) REFERENCES Project(ProjectID) ON DELETE CASCADE ON UPDATE CASCADE

)
CREATE TABE IF NOT EXISTS Complaints(
    ComplaintID VARCHAR(20) PRIMARY KEY,
    Titel VARCHAR(100) NOT NULL,
    Description TEXT NOT NULL,
    Status ENUM('Pending', 'In_Progress', 'Resolved', 'Closed') NOT NULL,
    UnitID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NOT NULL,
    UpdatedBy INT,
    FOREIGN KEY (CreatedBy) REFERENCES Users(CNIC) ON DELETE RESTRICT ON UPDATE CASCADE
    FOREIGN KEY (UpdatedBy) REFERENCES Users(CNIC) ON DELETE SET NULL  ON UPDATE CASCADE
    FOREIGN KEY (UnitID) REFERENCES Unit(UnitID) ON DELETE CASCADE ON UPDATE CASCADE

)
CREATE TABLE IF NOT EXISTS Documents(
    DocumnetID INT PRIMARY KEY ,
    DocumentType ENUM('Lease_Agreement', 'Maintenance_Request', 'Complaint_Record', 'Payment_Receipt,CNIC','NOC','UTILITY BILLS') NOT NULL,
    FileURl VARCHAR(255) NOT NULL,
    UploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UploadedBy INT NOT NULL,
    FOREIGN KEY (UploadedBy) REFERENCES Users(CNIC) ON DELETE CASCADE ON UPDATE CASCADE
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
CREATE TABLE IF NOT EXISTS DiscountRequest(
    RequestID INT PRIMARY KEY,
    UnitID INT NOT NULL,// Foreign key to Unit table
    RequestedAmount DECIMAL(10, 2) NOT NULL,
    Reason TEXT NOT NULL,
    Status ENUM('Pending', 'Approved', 'Rejected') NOT NULL,
    Remarks TEXT,
   
    CreatedBy INT NOT NULL,
    UpdatedBy INT,
    FOREIGN KEY (CreatedBy) REFERENCES Users(CNIC) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (UpdatedBy) REFERENCES Users(CNIC) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (UnitID) REFERENCES Unit(UnitID) ON DELETE CASCADE ON UPDATE CASCADE
)
CREATE TABLE IF NOT EXISTS Notice(
    NoticeID INT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description TEXT NOT NULL,
    CreatedBy INT NOT NULL,
    UpdatedBy INT,
    Status ENUM('Active', 'Expired') NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CreatedBy) REFERENCES Users(CNIC) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (UpdatedBy) REFERENCES Users(CNIC) ON DELETE SET NULL ON UPDATE CASCADE
)
-- User and Notice, Project and Notice have a many-to-many relationship, so we need separate associative tables for each.
-- We can't use a single table because one notice can be linked to multiple users, units, and projects.
-- Putting all these links in one table would make the structure confusing and hard to manage.

CREATE TABLE UserNotice (
    CNIC BIGINT,
    NoticeID INT,
    NoticeType ENUM('General', 'Urgent', 'Reminder') NOT NULL, 
    Status ENUM('NOT Acknowledged', 'Acknowledged') DEFAULT 'NOT Acknowledged',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CNIC, NoticeID),
    FOREIGN KEY (CNIC) REFERENCES Users(CNIC) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (NoticeID) REFERENCES Notice(NoticeID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE UnitNotice (
    UnitID INT,
    NoticeID INT,
    PRIMARY KEY (UnitID, NoticeID),
    NoticeType ENUM('General', 'Urgent', 'Reminder') NOT NULL, 
    Status ENUM('NOT Acknowledged', 'Acknowledged') DEFAULT 'NOT Acknowledged',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UnitID) REFERENCES Unit(UnitID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (NoticeID) REFERENCES Notice(NoticeID)  ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE ProjectNotice (
    ProjectID INT,
    NoticeID INT,
    NoticeType ENUM('General', 'Urgent', 'Reminder') NOT NULL, 
    Status ENUM('NOT Acknowledged', 'Acknowledged') DEFAULT 'NOT Acknowledged',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ProjectID, NoticeID),
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (NoticeID) REFERENCES Notice(NoticeID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS Project(
    ProjectID INT PRIMARY KEY NOT NULL,
    ProjectName VARCHAR(100) NOT NULL,
    Description TEXT NOT NULL,
    Status ENUM('Active', 'InActive') NOT NULL,
    CreatedBy INT NOT NULL,
    UpdatedBy INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CreatedBy) REFERENCES Users(CNIC) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (UpdatedBy) REFERENCES Users(CNIC) ON DELETE SET NULL ON UPDATE CASCADE
)
CREATE TABLE IF NOT EXISTS ProjectMembers(
    ProjectID INT NOT NULL,
    UserID INT NOT NULL,
    PRIMARY KEY (ProjectID, UserID),
    Role ENUM('Manager', 'Staff', 'Volunteer') NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(CNIC) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS UtilityBills(
    BillID INT PRIMARY KEY,
    UnitID INT NOT NULL,
    BillType ENUM('Electricity', 'Water', 'Gas', 'Internet') NOT NULL,
    BillUnits DECIMAL(10,2)
    Amount DECIMAL(10, 2) NOT NULL,
    BillMonth Date NOT NULL,
    DueDate DATE NOT NULL,
    PaymentDate DATE,

    PaidStatus ENUM('Paid', 'Unpaid') NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NOT NULL,
    UpdatedBy INT,
    FOREIGN KEY (CreatedBy) REFERENCES Users(CNIC) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (UpdatedBy) REFERENCES Users(CNIC) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (UnitID) REFERENCES Unit(UnitID) ON DELETE CASCADE ON UPDATE CASCADE
)